<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 */

namespace PromCMS\App\Models\Base;

enum CardType : string
{
  case GOAL_KEEPER = 'goalKeeper';
  case PLAYER = 'player';
  case MANAGER = 'manager';
}