<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 * Updates should be made to ../CardSizes.php as that is not overriden.
 */

namespace PromCMS\App\Models\Base;

use Doctrine\ORM\Mapping as ORM;
use PromCMS\Core\Database\Models\Mapping as PROM;
use PromCMS\Core\Database\Models\Abstract\Entity;

#[ORM\MappedSuperclass]
class CardSizes extends Entity
{
  use \PromCMS\Core\Database\Models\Trait\Ordable;
  use \PromCMS\Core\Database\Models\Trait\Ownable;
  use \PromCMS\Core\Database\Models\Trait\NumericId;
  
  #[ORM\Column(name: 'width', nullable: false, unique: false, type: 'integer'), PROM\PromModelColumn(title: 'Šířka (cm)', type: 'number', editable: false, hide: false, localized: false)]
  protected ?int $width;
  
  #[ORM\Column(name: 'height', nullable: false, unique: false, type: 'integer'), PROM\PromModelColumn(title: 'Výška (cm)', type: 'number', editable: false, hide: false, localized: false)]
  protected ?int $height;
  
  #[ORM\Column(name: 'price', nullable: false, unique: false, type: 'integer'), PROM\PromModelColumn(title: 'Cena', type: 'number', editable: false, hide: false, localized: false)]
  protected ?int $price;
  
  #[ORM\OneToOne(targetEntity: \PromCMS\App\Models\CardMaterial::class), ORM\JoinColumn(name: 'material_id', nullable: false, unique: false, referencedColumnName: 'id'), PROM\PromModelColumn(title: 'Materiál ', type: 'relationship', editable: false, hide: false, localized: false)]
  protected ?\PromCMS\App\Models\CardMaterial $material;
  
  #[ORM\ManyToOne(targetEntity: \PromCMS\Core\Database\Models\File::class), ORM\JoinColumn(name: 'image_id', nullable: false, unique: false, referencedColumnName: 'id'), PROM\PromModelColumn(title: 'Náhledový obrázek', type: 'file', editable: false, hide: false, localized: false)]
  protected ?\PromCMS\Core\Database\Models\File $image;
  
  function __construct()
  {
  }
  
  #[ORM\PostLoad]
  function __prom__initCollections()
  {
  }
  
  function getWidth(): int
  {
    return $this->width;
  }
  
  function setWidth(int $width): static
  {
    $this->width = $width;
    return $this;
  }
  
  function getHeight(): int
  {
    return $this->height;
  }
  
  function setHeight(int $height): static
  {
    $this->height = $height;
    return $this;
  }
  
  function getPrice(): int
  {
    return $this->price;
  }
  
  function setPrice(int $price): static
  {
    $this->price = $price;
    return $this;
  }
  
  function getMaterial(): \PromCMS\App\Models\CardMaterial
  {
    return $this->material;
  }
  
  function setMaterial(\PromCMS\App\Models\CardMaterial $material): static
  {
    $this->material = $material;
    return $this;
  }
  
  function getImage(): \PromCMS\Core\Database\Models\File
  {
    return $this->image;
  }
  
  function setImage(\PromCMS\Core\Database\Models\File $image): static
  {
    $this->image = $image;
    return $this;
  }
}