<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 * Updates should be made to ../CardBackgrounds.php as that is not overriden.
 */

namespace PromCMS\App\Models\Base;

use Doctrine\ORM\Mapping as ORM;
use PromCMS\Core\Database\Models\Mapping as PROM;
use PromCMS\Core\Database\Models\Abstract\Entity;

#[ORM\MappedSuperclass]
class CardBackgrounds extends Entity
{
  use \PromCMS\Core\Database\Models\Trait\Timestamps;
  use \PromCMS\Core\Database\Models\Trait\Ordable;
  use \PromCMS\Core\Database\Models\Trait\Ownable;
  use \PromCMS\Core\Database\Models\Trait\NumericId;
  
  #[ORM\Column(name: 'name', nullable: false, unique: true, type: 'string'), PROM\PromModelColumn(title: 'Název', type: 'string', editable: false, hide: false, localized: false)]
  protected ?string $name;
  
  #[ORM\ManyToOne(targetEntity: \PromCMS\Core\Database\Models\File::class), ORM\JoinColumn(name: 'image_id', nullable: false, unique: false, referencedColumnName: 'id'), PROM\PromModelColumn(title: 'Obrázek', type: 'file', editable: false, hide: false, localized: false)]
  protected ?\PromCMS\Core\Database\Models\File $image;
  
  #[ORM\Column(name: 'textcolor', nullable: false, unique: false, type: 'array'), PROM\PromModelColumn(title: 'Barva textu', type: 'json', editable: false, hide: false, localized: false)]
  protected ?array $textColor;
  
  #[ORM\ManyToOne(targetEntity: \PromCMS\App\Models\Sports::class, inversedBy: 'cardBackgrounds'), ORM\JoinColumn(name: 'sport_id', nullable: false, unique: false, referencedColumnName: 'id'), PROM\PromModelColumn(title: 'Sport', type: 'relationship', editable: false, hide: false, localized: false)]
  protected ?\PromCMS\App\Models\Sports $sport;
  
  function __construct()
  {
  }
  
  #[ORM\PostLoad]
  function __prom__initCollections()
  {
  }
  
  function getName(): string
  {
    return $this->name;
  }
  
  function setName(string $name): static
  {
    $this->name = $name;
    return $this;
  }
  
  function getImage(): \PromCMS\Core\Database\Models\File
  {
    return $this->image;
  }
  
  function setImage(\PromCMS\Core\Database\Models\File $image): static
  {
    $this->image = $image;
    return $this;
  }
  
  function getTextColor(): array
  {
    return $this->textColor;
  }
  
  function setTextColor(array $textColor): static
  {
    $this->textColor = $textColor;
    return $this;
  }
  
  function getSport(): \PromCMS\App\Models\Sports
  {
    return $this->sport;
  }
  
  function setSport(\PromCMS\App\Models\Sports $sport): static
  {
    $this->sport = $sport;
    return $this;
  }
}