<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 * Updates should be made to ../Carts.php as that is not overriden.
 */

namespace PromCMS\App\Models\Base;

use Doctrine\ORM\Mapping as ORM;
use PromCMS\Core\Database\Models\Mapping as PROM;
use Doctrine\Common\Collections\ArrayCollection;
use PromCMS\Core\Database\Models\Abstract\Entity;

#[ORM\MappedSuperclass]
class Carts extends Entity
{
  use \PromCMS\Core\Database\Models\Trait\Timestamps;
  use \PromCMS\Core\Database\Models\Trait\NumericId;
  
  #[ORM\Column(name: 'sessionid', nullable: false, unique: true, type: 'string'), PROM\PromModelColumn(title: 'Session', type: 'string', editable: false, hide: false, localized: false)]
  protected ?string $sessionId;
  /**
  * @var ArrayCollection<int, \PromCMS\App\Models\CartProducts>
  */
  
  #[ORM\OneToMany(targetEntity: \PromCMS\App\Models\CartProducts::class, mappedBy: 'cart'), PROM\PromModelColumn(title: 'Produkty', type: 'relationship', editable: false, hide: false, localized: false)]
  protected ?\Doctrine\Common\Collections\Collection $products;
  /**
  * @var ArrayCollection<int, \PromCMS\App\Models\Cards>
  */
  
  #[ORM\OneToMany(targetEntity: \PromCMS\App\Models\Cards::class, mappedBy: 'cart'), PROM\PromModelColumn(title: 'Karty', type: 'relationship', editable: false, hide: false, localized: false)]
  protected ?\Doctrine\Common\Collections\Collection $cards;
  
  #[ORM\ManyToOne(targetEntity: \PromCMS\App\Models\PromoCodes::class, inversedBy: 'carts'), ORM\JoinColumn(name: 'promocode_id', nullable: true, unique: false, referencedColumnName: 'id'), PROM\PromModelColumn(title: 'Promo Kod', type: 'relationship', editable: false, hide: false, localized: false)]
  protected ?\PromCMS\App\Models\PromoCodes $promoCode;
  
  function __construct()
  {
    $this->products = new ArrayCollection();
    $this->cards = new ArrayCollection();
  }
  
  #[ORM\PostLoad]
  function __prom__initCollections()
  {
    $this->products ??= new ArrayCollection();
    $this->cards ??= new ArrayCollection();
  }
  
  function getSessionId(): string
  {
    return $this->sessionId;
  }
  
  function setSessionId(string $sessionId): static
  {
    $this->sessionId = $sessionId;
    return $this;
  }
  
  function getProducts(): ?\Doctrine\Common\Collections\Collection
  {
    return $this->products;
  }
  
  function setProducts(?\Doctrine\Common\Collections\Collection $products): static
  {
    $this->products = $products;
    return $this;
  }
  
  function getCards(): ?\Doctrine\Common\Collections\Collection
  {
    return $this->cards;
  }
  
  function setCards(?\Doctrine\Common\Collections\Collection $cards): static
  {
    $this->cards = $cards;
    return $this;
  }
  
  function getPromoCode(): ?\PromCMS\App\Models\PromoCodes
  {
    return $this->promoCode;
  }
  
  function setPromoCode(?\PromCMS\App\Models\PromoCodes $promoCode): static
  {
    $this->promoCode = $promoCode;
    return $this;
  }
}