<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 * Updates should be made to ../Countries.php as that is not overriden.
 */

namespace PromCMS\App\Models\Base;

use Doctrine\ORM\Mapping as ORM;
use PromCMS\Core\Database\Models\Mapping as PROM;
use Doctrine\Common\Collections\ArrayCollection;
use PromCMS\Core\Database\Models\Abstract\Entity;

#[ORM\MappedSuperclass]
class Countries extends Entity
{
  use \PromCMS\Core\Database\Models\Trait\Ordable;
  use \PromCMS\Core\Database\Models\Trait\NumericId;
  
  #[ORM\Column(name: 'name', nullable: false, unique: true, type: 'string'), PROM\PromModelColumn(title: 'Název', type: 'string', editable: false, hide: false, localized: false)]
  protected ?string $name;
  
  #[ORM\ManyToOne(targetEntity: \PromCMS\Core\Database\Models\File::class), ORM\JoinColumn(name: 'flag_id', nullable: false, unique: false, referencedColumnName: 'id'), PROM\PromModelColumn(title: 'Vlajka', type: 'file', editable: false, hide: false, localized: false)]
  protected ?\PromCMS\Core\Database\Models\File $flag;
  /**
  * @var ArrayCollection<int, \PromCMS\App\Models\Cards>
  */
  
  #[ORM\OneToMany(targetEntity: \PromCMS\App\Models\Cards::class, mappedBy: 'country'), PROM\PromModelColumn(title: 'Karty', type: 'relationship', editable: false, hide: true, localized: false)]
  protected ?\Doctrine\Common\Collections\Collection $cards;
  
  function __construct()
  {
    $this->cards = new ArrayCollection();
  }
  
  #[ORM\PostLoad]
  function __prom__initCollections()
  {
    $this->cards ??= new ArrayCollection();
  }
  
  function getName(): string
  {
    return $this->name;
  }
  
  function setName(string $name): static
  {
    $this->name = $name;
    return $this;
  }
  
  function getFlag(): \PromCMS\Core\Database\Models\File
  {
    return $this->flag;
  }
  
  function setFlag(\PromCMS\Core\Database\Models\File $flag): static
  {
    $this->flag = $flag;
    return $this;
  }
  
  function getCards(): ?\Doctrine\Common\Collections\Collection
  {
    return $this->cards;
  }
  
  function setCards(?\Doctrine\Common\Collections\Collection $cards): static
  {
    $this->cards = $cards;
    return $this;
  }
}