<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 */

namespace PromCMS\App\Models\Base;

enum Currency : string
{
  case CZK = 'CZK';
  case EUR = 'EUR';
}