<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 * Updates should be made to ../FaqsTranslation.php as that is not overriden.
 */

namespace PromCMS\App\Models\Base;

use Doctrine\ORM\Mapping as ORM;
use PromCMS\Core\Database\Models\Mapping as PROM;
use Doctrine\Common\Collections\ArrayCollection;
use PromCMS\Core\Database\Models\Abstract\Entity;

#[ORM\MappedSuperclass]
class FaqsTranslation extends Entity
{
  use \PromCMS\Core\Database\Models\Trait\NumericId;
  use \PromCMS\Core\Database\Models\Trait\Timestamps;
  
  #[ORM\Column(type: 'string', name: 'locale', nullable: false)]
  protected string $locale;
  
  #[ORM\ManyToOne(targetEntity: \PromCMS\App\Models\Faqs::class, inversedBy: 'translations'), ORM\JoinColumn(name: 'object_id', nullable: false)]
  protected \PromCMS\App\Models\Faqs $object;
  
  #[ORM\Column(name: 'title', nullable: false, unique: true, type: 'string'), PROM\PromModelColumn(title: 'Titulek', type: 'string', editable: false, hide: false, localized: true)]
  protected ?string $title;
  
  #[ORM\Column(name: 'content', nullable: false, unique: false, type: 'text'), PROM\PromModelColumn(title: 'Obsah', type: 'longText', editable: false, hide: false, localized: true)]
  protected ?string $content;
  
  function __construct(string $locale)
  {
    $this->locale = $locale;
  }
  
  #[ORM\PostLoad]
  function __prom__initCollections()
  {
  }
  
  function getTitle(): string
  {
    return $this->title;
  }
  
  function setTitle(string $title): static
  {
    $this->title = $title;
    return $this;
  }
  
  function getContent(): string
  {
    return $this->content;
  }
  
  function setContent(string $content): static
  {
    $this->content = $content;
    return $this;
  }
  
  function setObject(\PromCMS\App\Models\Faqs $object): static
  {
    $this->object = $object;
    return $this;
  }
  
  function getLocale(): string
  {
    return $this->locale;
  }
}