<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 * Updates should be made to ../MainPageSlides.php as that is not overriden.
 */

namespace PromCMS\App\Models\Base;

use Doctrine\ORM\Mapping as ORM;
use PromCMS\Core\Database\Models\Mapping as PROM;
use PromCMS\Core\Database\Models\Abstract\Entity;

#[ORM\MappedSuperclass]
class MainPageSlides extends Entity
{
  use \PromCMS\Core\Database\Models\Trait\Ordable;
  use \PromCMS\Core\Database\Models\Trait\Ownable;
  use \PromCMS\Core\Database\Models\Trait\NumericId;
  
  #[ORM\Column(name: 'title', nullable: false, unique: true, type: 'string'), PROM\PromModelColumn(title: 'Titulek', type: 'string', editable: false, hide: false, localized: false)]
  protected ?string $title;
  
  #[ORM\Column(name: 'subtitle', nullable: true, unique: false, type: 'string'), PROM\PromModelColumn(title: 'Subtitulek', type: 'string', editable: false, hide: false, localized: false)]
  protected ?string $subTitle;
  
  #[ORM\Column(name: 'buttonurl', nullable: true, unique: false, type: 'array'), PROM\PromModelColumn(title: 'Tlačítko', type: 'json', editable: false, hide: false, localized: false)]
  protected ?array $buttonUrl;
  
  #[ORM\Column(name: 'image_id', nullable: false, unique: false, type: 'integer'), PROM\PromModelColumn(title: 'Obrázek', type: 'file', editable: false, hide: false, localized: false)]
  protected ?\PromCMS\Core\Database\Models\File $image;
  
  function __construct()
  {
  }
  
  #[ORM\PostLoad]
  function __prom__initCollections()
  {
  }
  
  function getTitle(): string
  {
    return $this->title;
  }
  
  function setTitle(string $title): static
  {
    $this->title = $title;
    return $this;
  }
  
  function getSubTitle(): ?string
  {
    return $this->subTitle;
  }
  
  function setSubTitle(?string $subTitle): static
  {
    $this->subTitle = $subTitle;
    return $this;
  }
  
  function getButtonUrl(): ?array
  {
    return $this->buttonUrl;
  }
  
  function setButtonUrl(?array $buttonUrl): static
  {
    $this->buttonUrl = $buttonUrl;
    return $this;
  }
  
  function getImage(): \PromCMS\Core\Database\Models\File
  {
    return $this->image;
  }
  
  function setImage(\PromCMS\Core\Database\Models\File $image): static
  {
    $this->image = $image;
    return $this;
  }
}