<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 * Updates should be made to ../NewsletterSubscriptions.php as that is not overriden.
 */

namespace PromCMS\App\Models\Base;

use Doctrine\ORM\Mapping as ORM;
use PromCMS\Core\Database\Models\Mapping as PROM;
use PromCMS\Core\Database\Models\Abstract\Entity;

#[ORM\MappedSuperclass]
class NewsletterSubscriptions extends Entity
{
  use \PromCMS\Core\Database\Models\Trait\Timestamps;
  use \PromCMS\Core\Database\Models\Trait\NumericId;
  
  #[ORM\Column(name: 'email', nullable: false, unique: true, type: 'string'), PROM\PromModelColumn(title: 'Email', type: 'string', editable: false, hide: false, localized: false)]
  protected ?string $email;
  
  function __construct()
  {
  }
  
  #[ORM\PostLoad]
  function __prom__initCollections()
  {
  }
  
  function getEmail(): string
  {
    return $this->email;
  }
  
  function setEmail(string $email): static
  {
    $this->email = $email;
    return $this;
  }
}