<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 */

namespace PromCMS\App\Models\Base;

enum OrderState : string
{
  case CREATED = 'vytvořeno';
  case UNPAID = 'nezaplaceno';
  case NOT_VERIFIED = 'nepotvrzeno';
  case VERIFIED = 'potvrzeno';
  case ABANDONED = 'zrušeno';
  case FINISHED = 'dokončeno';
}